In [1]:
import pandas as pd, os

os.chdir(r"C:\Users\Melanie\OneDrive - Rensselaer Polytechnic Institute\Desktop\School\24_Spring\Data Analytics\DA_Project\Old Datasets")
pubinv = pd.read_excel("heat_gen.xlsx",skiprows=1)

# #remove the last few rows
# pubinv.drop(pubinv.tail(24).index, inplace = True)

# #rename the headers
# pubinv = pubinv.rename(columns = {"Unnamed: 0": "Country",
#                                   "Unnamed: 1": "Technology",
#                                   "Unnamed: 2": "Year",
#                                   "Unnamed: 3": "Amount"})

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [2]:
"""time to fill the the missing country"""
all_countries = list(pubinv["Country"].dropna())

for i in range(len(all_countries)-1):
    start_index = pubinv[pubinv["Country"] == all_countries[i]].index[0]
    end_index = pubinv[pubinv["Country"] == all_countries[i+1]].index[0]
    pubinv.loc[start_index:end_index-1, "Country"] = all_countries[i]
    
#fill the last subset
pubinv["Country"] = pubinv["Country"].fillna(all_countries[-1])

In [ ]:
#time to fill in the technologies
n = len(all_countries)
technologies = list(pubinv[pubinv["Country"] == all_countries[0]]["Technology"].dropna())

for j in range(n):
    for i in range(len(technologies)-1):
        start_index = pubinv[pubinv["Technology"] == technologies[i]].index[j]
        end_index = pubinv[pubinv["Technology"] == technologies[i+1]].index[j]
        pubinv.loc[start_index:end_index-1, "Technology"] = technologies[i]
    
    if j < n:
        #fill the last subset by finding the location of the start of the next country
        last_index = pubinv[pubinv["Technology"] == technologies[0]].index[j+1]
        pubinv.loc[end_index:last_index-1,"Technology"] = technologies[0]
#fill in the last part using fillna
pubinv["Technology"].fillna(technologies[-1],inplace=True)

In [6]:
pubinv

           Country                  Technology    Year  Amount
0      Afghanistan  On-grid Solar photovoltaic  2000.0     0.0
1      Afghanistan  On-grid Solar photovoltaic  2001.0     0.1
2      Afghanistan  On-grid Solar photovoltaic  2002.0     0.0
3      Afghanistan  On-grid Solar photovoltaic  2003.0     0.0
4      Afghanistan  On-grid Solar photovoltaic  2004.0     0.0
...            ...                         ...     ...     ...
93319     Zimbabwe                         NaN  2017.0     0.0
93320     Zimbabwe                         NaN  2018.0     0.0
93321     Zimbabwe                         NaN  2019.0     0.0
93322     Zimbabwe                         NaN  2020.0     0.0
93323     Zimbabwe                         NaN  2021.0     0.0

[93324 rows x 4 columns]

In [ ]:
asdf = pubinv[pubinv["Country"] == "Afghanistan"]


# asdf.pivot_table(index=["Country","Year"], columns='Technology', values='Amount',aggfunc="sum")

In [ ]:
pubinv.pivot_table(index=["Year"], columns='Technology', values='Amount',aggfunc="sum")

In [42]:
ag = pubinv.pivot_table(index=["Country","Year"], columns='Technology', values='Amount',aggfunc="sum")
ag

Technology          Biogas  Coal and peat  Concentrated solar power  \
Country     Year
Afghanistan 2000.0     NaN            NaN                       NaN
            2001.0     NaN            NaN                       NaN
            2002.0     NaN            NaN                       NaN
            2003.0     NaN            NaN                       NaN
            2004.0     NaN            NaN                       NaN
...                    ...            ...                       ...
Zimbabwe    2017.0     NaN            NaN                       NaN
            2018.0     NaN            NaN                       NaN
            2019.0     NaN            NaN                       NaN
            2020.0     NaN            NaN                       NaN
            2021.0     NaN            NaN                       NaN

Technology          Fossil fuels n.e.s.  Geothermal energy  Liquid biofuels  \
Country     Year
Afghanistan 2000.0                  NaN                NaN              NaN
            2001.0                  NaN                NaN              NaN
            2002.0                  NaN                NaN              NaN
            2003.0                  NaN                NaN              NaN
            2004.0                  NaN                NaN              NaN
...                                 ...                ...              ...
Zimbabwe    2017.0                  NaN                NaN              NaN
            2018.0                  NaN                NaN              NaN
            2019.0                  NaN                NaN              NaN
            2020.0                  NaN                NaN              NaN
            2021.0                  NaN                NaN              NaN

Technology          Marine energy  Multiple renewables*  Natural gas  \
Country     Year
Afghanistan 2000.0            NaN                   NaN          NaN
            2001.0            NaN                   NaN          NaN
            2002.0            NaN                   NaN          NaN
            2003.0            NaN                   NaN          NaN
            2004.0            NaN                   NaN          NaN
...                           ...                   ...          ...
Zimbabwe    2017.0            NaN                   NaN          NaN
            2018.0            NaN                   NaN          NaN
            2019.0            NaN                   NaN          NaN
            2020.0            NaN                   NaN          NaN
            2021.0            NaN                   NaN          NaN

Technology          Non-renewable municipal waste  ...  \
Country     Year                                   ...
Afghanistan 2000.0                            NaN  ...
            2001.0                            NaN  ...
            2002.0                            NaN  ...
            2003.0                            NaN  ...
            2004.0                            NaN  ...
...                                           ...  ...
Zimbabwe    2017.0                            NaN  ...
            2018.0                            NaN  ...
            2019.0                            NaN  ...
            2020.0                            NaN  ...
            2021.0                            NaN  ...

Technology          Off-grid Solar photovoltaic  Offshore wind energy  Oil  \
Country     Year
Afghanistan 2000.0                          NaN                   NaN  NaN
            2001.0                          NaN                   NaN  NaN
            2002.0                          NaN                   NaN  NaN
            2003.0                          NaN                   NaN  NaN
            2004.0                          NaN                   NaN  NaN
...                                         ...                   ...  ...
Zimbabwe    2017.0                          NaN                   NaN  NaN
            2018.0                          NaN                   NaN  NaN
            2019.0                          NaN                   NaN  NaN
            2020.0                          NaN                   NaN  NaN
            2021.0                          NaN                   NaN  NaN

Technology          On-grid Solar photovoltaic  Onshore wind energy  \
Country     Year
Afghanistan 2000.0                        0.02                  NaN
            2001.0                        0.12                  NaN
            2002.0                       16.12                  NaN
            2003.0                       26.77                  NaN
            2004.0                       61.65                  NaN
...                                        ...                  ...
Zimbabwe    2017.0                        5.81                  NaN
            2018.0                      956.65                  NaN
            2019.0                        0.25                  NaN
            2020.0                        0.07                  NaN
            2021.0                        0.00                  NaN

Technology          Other primary solid biofuels n.e.s.  Pumped storage  \
Country     Year
Afghanistan 2000.0                                  NaN             NaN
            2001.0                                  NaN             NaN
            2002.0                                  NaN             NaN
            2003.0                                  NaN             NaN
            2004.0                                  NaN             NaN
...                                                 ...             ...
Zimbabwe    2017.0                                  NaN             NaN
            2018.0                                  NaN             NaN
            2019.0                                  NaN             NaN
            2020.0                                  NaN             NaN
            2021.0                                  NaN             NaN

Technology          Renewable hydropower  Renewable municipal waste  \
Country     Year
Afghanistan 2000.0                   NaN                        NaN
            2001.0                   NaN                        NaN
            2002.0                   NaN                        NaN
            2003.0                   NaN                        NaN
            2004.0                   NaN                        NaN
...                                  ...                        ...
Zimbabwe    2017.0                   NaN                        NaN
            2018.0                   NaN                        NaN
            2019.0                   NaN                        NaN
            2020.0                   NaN                        NaN
            2021.0                   NaN                        NaN

Technology          Solar thermal energy
Country     Year
Afghanistan 2000.0                   NaN
            2001.0                   NaN
            2002.0                   NaN
            2003.0                   NaN
            2004.0                   NaN
...                                  ...
Zimbabwe    2017.0                   NaN
            2018.0                   NaN
            2019.0                   NaN
            2020.0                   NaN
            2021.0                   NaN

[4444 rows x 21 columns]

In [43]:
data = {'Country': ['USA', 'USA', 'USA', 'UK', 'UK', 'UK', 'Canada', 'Canada', 'Canada',
                    'USA', 'USA', 'USA', 'UK', 'UK', 'UK', 'Canada', 'Canada', 'Canada'],
        'Technology': ['Tech1', 'Tech2', 'Tech3', 'Tech1', 'Tech2', 'Tech3', 'Tech1', 'Tech2', 'Tech3',
                       'Tech1', 'Tech2', 'Tech3', 'Tech1', 'Tech2', 'Tech3', 'Tech1', 'Tech2', 'Tech3'],
        'Year': [2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020,
                 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021],
        'Money_Put_In': [100, 150, 200, 120, 180, 240, 90, 130, 170,
                         101, 141,200,204,203,203,2,13,14]}
df = pd.DataFrame(data)

# Reshape the DataFrame using pivot_table with fill_value
pivot_df = df.pivot_table(index=["Country","Year"], columns='Technology', values='Money_Put_In',aggfunc="sum")

# Display the resulting DataFrame
print(pivot_df)

Technology    Tech1  Tech2  Tech3
Country Year
Canada  2020     90    130    170
        2021      2     13     14
UK      2020    120    180    240
        2021    204    203    203
USA     2020    100    150    200
        2021    101    141    200

In [146]:
pubinv.pivot_table(index=["Country","Year"], columns='Technology', values='Amount',aggfunc='sum')

Technology          Biogas  Coal and peat  Concentrated solar power  \
Country     Year
Afghanistan 2000.0     0.0            0.0                       0.0
            2001.0     0.0            0.0                       0.0
            2002.0     0.0            0.0                       0.0
            2003.0     0.0            0.0                       0.0
            2004.0     0.0            0.0                       0.0
...                    ...            ...                       ...
Zimbabwe    2017.0     NaN            NaN                       NaN
            2018.0     NaN            NaN                       NaN
            2019.0     NaN            NaN                       NaN
            2020.0     NaN            NaN                       NaN
            2021.0     NaN            NaN                       NaN

Technology          Fossil fuels n.e.s.  Geothermal energy  Liquid biofuels  \
Country     Year
Afghanistan 2000.0                 0.00                0.0              0.0
            2001.0                 0.00                0.0              0.0
            2002.0                12.03                0.0              0.0
            2003.0                 0.10                0.0              0.0
            2004.0                61.65                0.0              0.0
...                                 ...                ...              ...
Zimbabwe    2017.0                  NaN                NaN              NaN
            2018.0                  NaN                NaN              NaN
            2019.0                  NaN                NaN              NaN
            2020.0                  NaN                NaN              NaN
            2021.0                  NaN                NaN              NaN

Technology          Marine energy  Multiple renewables*  Natural gas  \
Country     Year
Afghanistan 2000.0            0.0                  0.00          0.0
            2001.0            0.0                  0.00          0.0
            2002.0            0.0                  0.00          0.0
            2003.0            0.0                 26.38          0.0
            2004.0            0.0                  0.00          0.0
...                           ...                   ...          ...
Zimbabwe    2017.0            NaN                   NaN          NaN
            2018.0            NaN                   NaN          NaN
            2019.0            NaN                   NaN          NaN
            2020.0            NaN                   NaN          NaN
            2021.0            NaN                   NaN          NaN

Technology          Non-renewable municipal waste  ...  \
Country     Year                                   ...
Afghanistan 2000.0                            0.0  ...
            2001.0                            0.0  ...
            2002.0                            0.0  ...
            2003.0                            0.0  ...
            2004.0                            0.0  ...
...                                           ...  ...
Zimbabwe    2017.0                            NaN  ...
            2018.0                            NaN  ...
            2019.0                            NaN  ...
            2020.0                            NaN  ...
            2021.0                            NaN  ...

Technology          Off-grid Solar photovoltaic  Offshore wind energy  Oil  \
Country     Year
Afghanistan 2000.0                          0.0                   0.0  0.0
            2001.0                          0.0                   0.0  0.0
            2002.0                          0.0                   0.0  0.0
            2003.0                          0.0                   0.0  0.0
            2004.0                          0.0                   0.0  0.0
...                                         ...                   ...  ...
Zimbabwe    2017.0                          NaN                   NaN  NaN
            2018.0                          NaN                   NaN  NaN
            2019.0                          NaN                   NaN  NaN
            2020.0                          NaN                   NaN  NaN
            2021.0                          NaN                   NaN  NaN

Technology          On-grid Solar photovoltaic  Onshore wind energy  \
Country     Year
Afghanistan 2000.0                         0.0                  0.0
            2001.0                         0.1                  0.0
            2002.0                         0.0                  0.0
            2003.0                         0.0                  0.0
            2004.0                         0.0                  0.0
...                                        ...                  ...
Zimbabwe    2017.0                         NaN                  NaN
            2018.0                         NaN                  NaN
            2019.0                         NaN                  NaN
            2020.0                         NaN                  NaN
            2021.0                         NaN                  NaN

Technology          Other primary solid biofuels n.e.s.  Pumped storage  \
Country     Year
Afghanistan 2000.0                                  0.0             0.0
            2001.0                                  0.0             0.0
            2002.0                                  0.0             0.0
            2003.0                                  0.0             0.0
            2004.0                                  0.0             0.0
...                                                 ...             ...
Zimbabwe    2017.0                                  NaN             NaN
            2018.0                                  NaN             NaN
            2019.0                                  NaN             NaN
            2020.0                                  NaN             NaN
            2021.0                                  NaN             NaN

Technology          Renewable hydropower  Renewable municipal waste  \
Country     Year
Afghanistan 2000.0                  0.02                        0.0
            2001.0                  0.02                        0.0
            2002.0                  4.09                        0.0
            2003.0                  0.29                        0.0
            2004.0                  0.00                        0.0
...                                  ...                        ...
Zimbabwe    2017.0                   NaN                        NaN
            2018.0                   NaN                        NaN
            2019.0                   NaN                        NaN
            2020.0                   NaN                        NaN
            2021.0                   NaN                        NaN

Technology          Solar thermal energy
Country     Year
Afghanistan 2000.0                   0.0
            2001.0                   0.0
            2002.0                   0.0
            2003.0                   0.0
            2004.0                   0.0
...                                  ...
Zimbabwe    2017.0                   NaN
            2018.0                   NaN
            2019.0                   NaN
            2020.0                   NaN
            2021.0                   NaN

[4444 rows x 21 columns]